<div class="container">
    <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <? $account = $this->auth()->getManager(); ?>
        <!-- Begin section Navbar -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#header-collapse">
                <span class="sr-only">Toggle navigation</span>
                <i class="fa fa-bars"></i>
            </button>
            <!-- Logo -->
            <a class="navbar-brand lang-<?=$this->layout()->userLang ?>" href="<?=$this->url('home')?>">IxTheo</a>
        </div>
        <? if (!isset($this->layout()->renderingError)): ?>
            <div class="collapse navbar-collapse" id="header-collapse">
                <nav>
                    <ul class="nav navbar-nav navbar-right flip">

                        <!-- Images for supporters   -->

                        <!-- Begin section Main Menu -->
                        <li role="presentation" class="active">
                            <a href="<?=$this->url('home')?>">
                                <i class="fa fa-home" aria-hidden="true"></i>
                                <?=$this->transEsc('Home');?>
                            </a>
                        </li>
                        <li role="presentation" class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown"  href="#" role="button" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-info-circle"></i>
                                <?=$this->transEsc('About');?> <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="/Impressum"><?=$this->transEsc('Impressum');?></a></li>
                            </ul>
                        </li>

                        <!-- Begin Help dropdown -->
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
                               aria-expanded="false">
                                <i class="fa fa-question-circle" aria-hidden="true"></i> Help<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="A-Z"> IxTheo A-Z</a></li>
                                <? if ($this->feedback()->tabEnabled()): ?>
                                    <li>
                                        <a id="feedbackLink" class="modal-link" href="<?= $this->url('feedback-home') ?>"><i
                                                    class="fa fa-envelope"></i> <?= $this->transEsc("Feedback") ?></a>
                                    </li>
                                <? endif; ?>

                                <? $cart = $this->cart();
                                if ($cart->isActive()): ?>
                                    <li id="cartSummary">
                                        <a id="cartItems" class="modal-link" title="<?= $this->transEsc('View Book Bag') ?>"
                                           href="<?= $this->url('cart-home') ?>"><i class="fa fa-suitcase"></i>
                                            <strong><?= count($cart->getItems()) ?></strong> <?= $this->transEsc('items') ?><?= $cart->isFull() ? ' (' . $this->transEsc('bookbag_full') . ')' : '' ?>
                                        </a>
                                    </li>
                                <? endif; ?>
                            </ul>
                        </li>
                        <!-- End Help dropdown -->

                        <!-- Begin section user account -->
                        <? if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
                            <li class="logoutOptions<? if(!$account->isLoggedIn()): ?> hidden<? endif ?>">
                                <a href="<?=$this->url('myresearch-home', array(), array('query' => array('redirect' => 0)))?>" class="modal-link" title="<?=$this->transEsc("Your Account")?>"><i class="fa fa-home"></i> <?=$this->transEsc("Your Account")?></a>
                            </li>
                            <li class="logoutOptions<? if(!$account->isLoggedIn()): ?> hidden<? endif ?>">
                                <a href="<?=$this->url('myresearch-logout')?>" class="modal-link" title="<?=$this->transEsc("Log Out")?>"><i class="fa fa-sign-out"></i> <?=$this->transEsc("Log Out")?></a>
                            </li>
                            <li id="loginOptions"<? if($account->isLoggedIn()): ?> class="hidden"<? endif ?>>
                                <? if ($sessionInitiator = $account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))): ?>
                                    <a href="<?=$this->escapeHtmlAttr($sessionInitiator)?>"><i class="fa fa-sign-in"></i> <?=$this->transEsc("Institutional Login")?></a>
                                <? else: ?>
                                    <a href="<?=$this->url('myresearch-userlogin')?>" class="modal-link" data-lightbox title="<?=$this->transEsc("Login")?>"><i class="fa fa-sign-in"></i> <?=$this->transEsc("Login")?></a>
                                <? endif; ?>
                            </li>
                        <? endif; ?>
                        <!-- End section user account -->

                        <!-- Begin section language   -->
                        <? if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
                            <li class="dropdown">
                                <form method="post" name="langForm" id="langForm">
                                    <input type="hidden" name="mylang"/>
                                </form>
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-globe" aria-hidden="true"></i> <?=$this->transEsc("Language")?> <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <? foreach ($this->layout()->allLangs as $langCode => $langName): ?>
                                        <li<?=$this->layout()->userLang == $langCode ? ' class="active"' : ''?>><a href="#" onClick="document.langForm.mylang.value='<?=$langCode?>';document.langForm.submit()"><?=$this->displayLanguageOption($langName)?></a></li>
                                    <? endforeach; ?>
                                </ul>
                            </li>
                        <? endif; ?>
                        <!-- End section language  -->

                        <!-- End section Main Menu -->
                    </ul>
                </nav>
            </div>
        <? endif; ?>
        <!--   End section Navbar     -->
    </div><!-- close col's -->
</div><!-- close row -->
</div><!-- close container -->

<div class="container-fluid no-padding">
    <div class="row-fluid no-padding">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 no-padding">
            <!--  Begin section searchbar -->
            <section class="visible-lg section-home">
                <div class="panel-home">

                    <div class="container vertical-center">
                    <br />
                    <br />

                    <!--  Begin title -->
                    <h1>
                        <a href="<?=$this->url('home')?>" title="Index Theologicus">Index Theologicus</a>
                    </h1>
                    <small><?=$this->transEsc("ixtheo_subtitle")?></small>
                    <!-- End title -->

                    <br />
                    <? if ($this->ils()->getOfflineMode() == "ils-offline"): ?>
                        <div class="alert alert-warning">
                            <h2><?= $this->transEsc('ils_offline_title') ?></h2>

                            <p><strong><?= $this->transEsc('ils_offline_status') ?></strong></p>

                            <p><?= $this->transEsc('ils_offline_home_message') ?></p>
                            <? $supportEmail = $this->escapeHtmlAttr($this->systemEmail()); ?>
                            <p><a href="mailto:<?= $supportEmail ?>"><?= $supportEmail ?></a></p>
                        </div>
                    <? endif; ?>
                    <div class="clearfix searchbox_home" role="search">
                        <?=$this->layout()->searchbox ?>
                    </div>
                </div><!-- close container -->
        </div><!-- close panel-home -->
        </section>
        <!-- End section searchbar -->
    </div><!-- close col's -->
</div><!-- close row -->
</div><!-- close container -->