<div class="background-lightblue">
    <div class="container">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

            <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 panel panel-top panel-inverse">
                <div class="panel-image-wrapper"><img src="/themes/ixTheoTheme/images/Temple_Scroll.png" alt="" class="img-responsive panel-image" /></div>
                <div class="panel-content">
                    <h4>Aktuelles</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. At ea obcaecati quia quibusdam tempora!</p>
                    <a href="#" class="btn btn-inverse" role="button">Weiterlesen</a>
                </div>
            </div>

            <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 panel panel-top panel-default">
                <div class="panel-image-wrapper"><img src="/themes/ixTheoTheme/images/Martin_Luther.jpg" alt="" class="img-responsive panel-image"></div>
                <div class="panel-content">
                    <h4>IxTheo entdecken</h4>
                    <p>A accusamus ad aliquam animi, at beatae consectetur dolore dolores, doloribus est eum ex harum illum ipsam.</p>
                    <a href="#" class="btn btn-default" role="button">Mehr erfahren</a>
                </div>
            </div>

            <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 panel panel-top panel-default">
                <div class="panel-image-wrapper"><img src="/themes/ixTheoTheme/images/800px-Martin_Luther_King_Jr_NYWTS.jpg" alt="" class="img-responsive panel-image"></div>
                <div class="panel-content">
                    <h4>IxTheo Repositories</h4>
                    <p>Accusamus assumenda at aut commodi cumque doloribus iste labore laborum magni molestiae mollitia neque.</p>
                    <a href="#" class="btn btn-default" role="button">Weiterlesen</a>
                </div>
            </div>

            <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 panel-buttons">
                <div class="row panel-button">
                    <a href="#" class="btn btn-primary">IxTheo Journals</a>
                </div>
                <div class="row panel-button">
                    <a href="#" class="btn btn-primary">IxTheo Bible</a>
                </div>
                <div class="row panel-button">
                    <a href="#" class="btn btn-primary">KirchenRecht</a>
                </div>
                <div class="row panel-button">
                    <a href="#" class="btn btn-primary">Augustinus</a>
                </div>
            </div>
        </div>

</div>
</div>

<br />

<div class="background-lightblue">
    <div class="container">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

            <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 panel panel-bottom panel-default">
                <div class="panel-image-wrapper"><img src="/themes/ixTheoTheme/images/Temple_Scroll.png" alt="Bild Verlage" class="img-responsive panel-image" /></div>
                <div class="panel-content">
                    <h4>Für Verlage</h4>
                    <p>Was bietet IxTheo für Verlage?</p>
                    <a href="#" class="btn btn-default" role="button">Mehr erfahren</a>
                </div>
            </div>

            <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 panel panel-bottom panel-default">
                <div class="panel-image-wrapper"><img src="/themes/ixTheoTheme/images/Temple_Scroll.png" alt="Bild Autoren" class="img-responsive panel-image" /></div>
                <div class="panel-content">
                    <h4>Für Autoren</h4>
                    <p>Wie können Autoren ihre Artikel auf IxTheo veröffentlichen?</p>
                    <a href="#" class="btn btn-default" role="button">Mehr erfahren</a>
                </div>
            </div>

            <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 panel panel-bottom panel-default">
                <div class="panel-image-wrapper"><img src="/themes/ixTheoTheme/images/Temple_Scroll.png" alt="Bild Herausgeber" class="img-responsive panel-image" /></div>
                <div class="panel-content">
                    <h4>Für Herausgeber</h4>
                    <p>Was bietet IxTheo für Herausgeber?</p>
                    <a href="#" class="btn btn-default" role="button">Mehr erfahren</a>
                </div>
            </div>

            <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 panel panel-bottom panel-default">
                <div class="panel-image-wrapper"><img src="/themes/ixTheoTheme/images/Temple_Scroll.png" alt="Bild Bibliothekare" class="img-responsive panel-image" /></div>
                <div class="panel-content">
                    <h4>Für Bibliothekare</h4>
                    <p>Was bietet IxTheo für Bibliothekare?</p>
                    <a href="#" class="btn btn-default" role="button">Mehr erfahren</a>
                </div>
            </div>

        </div></div></div>