<div class="row footer">
    <div class="col-sm-4">
        <ul class="bottom-menu">
            <li><a href="#"><?=$this->transEsc('Search')?></a></li>
            <li><a href="<?=$this->url('search-history')?>"><?=$this->transEsc('Search History')?></a></li>
            <li><a href="<?=$this->url('search-advanced')?>"><?=$this->transEsc('Advanced Search')?></a></li>
            <li><a href="<?=$this->url('help-home')?>?topic=search" data-lightbox class="help-link" title="<?=$this->transEsc('Search Tips')?>"><?=$this->transEsc('Search Tips')?></a></li>
            <li><a href="<?=$this->url('help-faq')?>"><?=$this->transEsc('FAQs')?></a></li>
            <li><a href="<?=$this->url('keywordchainsearch-home')?>"><?=$this->transEsc('Browse Keywordchains')?></a></li>
            <li><a href="<?=$this->url('browse-home')?>"><?=$this->transEsc('Browse the Catalog')?></a></li>
            <li><a href="<?=$this->url('alphabrowse-home')?>"><?=$this->transEsc('Browse Alphabetically')?></a></li>
            <li><a href="#"><?=$this->transEsc('Account')?></a></li>
        </ul>

    </div>
    <div class="col-sm-4">

        <ul class="bottom-menu">
            <li><a href="#">About us</a></li>
            <li><a href="#">Press</></li>
            <li><a href="#">Team</a></li>
            <li><a href="#">For publishers</a></li>
            <li><a href="#">Supporters</a></li>
        </ul>

    </div>
    <div class="col-sm-4">
        <h4>Contact</h4>
        <p>Index Theologicus</p>
        <br />
        <p>Dr. Martin Faßnacht</p>
        <p><i class="fa fa-phone"></i> +49 (0)7071 2974029</p>
        <p><i class="fa fa-envelope"></i> ixtheo@ub.uni-tuebingen.de</p>
        <br />
        <h5>Department Media Processing II</h5>
        <p>IxTheo / Cataloging</p>
        <p><i class="fa fa-phone"></i> +49 (0)7071 2972847</p>
        <p><i class="fa fa-envelope"></i> ixtheo@ub.uni-tuebingen.de</p>

        <a href="/Feedback/home" class="">Contact us</a>

    </div>
</div>
