<hr />
<div class="row">
    <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
        &copy <? printf(date('o')); ?> Index Theologicus
    </div>
    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
        <ul class="footer-menu">
            <li><a href="#">Imprint</a></li>
            <li><a href="#">Privacy Policy</a></li>
            <li><a href="#">Sitemap</a></li>
        </ul>
    </div>
</div>
